### ISSUE TITLE
ESE - read_sid big endian for the RID (last) part

### ISSUE THREAD

**Issue by almandin** [fox-it/dissect.util#23]
Hi,

I've managed to find something intriguing. I'm parsing NTDS databases with Dissect.esedb and I'm seeing differences between the SIDs I'm obtaining from `dissect.utils.sid.read_sid` and the real sid gotten from `get-aduser` directly on my domain controller. I found this issue while inspecting groups SIDs and could not find known SID (ending with -512 for domain admins for example).

The main issue seems to come from endianness, though fixing it would require not to comply with Microsoft documentation and that's what is strange.

What I'm doing:

```python
print(domain_object.get(ese_db.column_names["objectSid"]))
print(sid.read_sid(domain_object.get(ese_db.column_names["objectSid"])))
```

(I put the column names inside the database object to access them by name without using `ATT` column names)

What I get
```
b'\x01\x04\x00\x00\x00\x00\x00\x05\x15\x00\x00\x00\xefr\x9d\x96p\x15\xd5\xa1\xdazQ\xe8'
S-1-5-21-2526900975-2715096432-3897653978
```

What I expect:

![image](https://user-images.githubusercontent.com/9830129/235461748-bfdfd973-da4f-4b8a-96c1-39f3eb4ae532.png)

The fix is to always consider the last subpart of the SID in big endian instead of little endian, though I see this documented nowhere. It is always said that all subauthority parts are stored in little endian...

My alternative function:
```python
def read_sid(raw):
    rev = str(int(raw[0]))
    nb_dashes = int(raw[1])
    id_auth_value = int.from_bytes(raw[2:8], "big")
    subparts = []
    for i in range(nb_dashes):
        endianess = "big" if i == nb_dashes - 1 else "little"
        subparts.append(str(int.from_bytes(raw[8+(i\*4):8+(i\*4)+4], endianess)))
    return f"S-{rev}~~{id_auth_value}~~{'-'.join(subparts)}"
```

If anyone is able to see somewhere why it would need to be in big endian for the last part, it would be nice, maybe it's an error in the dissect's ESE module ?
Thanks.

**Comment by Schamper** [comment]
Interesting. We have some projects for parsing the NTDS.dit as well (scheduled to be open-sourced down the road too!) but I don't remember encountering this issue. I'll need to reference test this. I'll be out of office for a while though, so it'll take a bit longer :smile:
